# Generated by Django 3.0.2 on 2020-01-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200125_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='my tilte', max_length=30),
            preserve_default=False,
        ),
    ]
