# Generated by Django 3.0.2 on 2020-02-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_clap'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='claps_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
