# Generated by Django 3.0.2 on 2020-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='claps_count',
            field=models.IntegerField(default=0),
        ),
    ]
